USE asset_management;

DROP INDEX `name_2` ON `categories`;
DROP INDEX `name_3` ON `categories`;
DROP INDEX `name_4` ON `categories`;
DROP INDEX `name_5` ON `categories`;
DROP INDEX `name_6` ON `categories`;
DROP INDEX `name_7` ON `categories`;
DROP INDEX `name_8` ON `categories`;
DROP INDEX `name_9` ON `categories`;
DROP INDEX `name_10` ON `categories`;
DROP INDEX `name_11` ON `categories`;
DROP INDEX `name_12` ON `categories`;
DROP INDEX `name_13` ON `categories`;
DROP INDEX `name_14` ON `categories`;
DROP INDEX `name_15` ON `categories`;
DROP INDEX `name_16` ON `categories`;
DROP INDEX `name_17` ON `categories`;
DROP INDEX `name_18` ON `categories`;
DROP INDEX `name_19` ON `categories`;
DROP INDEX `name_20` ON `categories`;
DROP INDEX `name_21` ON `categories`;
DROP INDEX `name_22` ON `categories`;
DROP INDEX `name_23` ON `categories`;
DROP INDEX `name_24` ON `categories`;
DROP INDEX `name_25` ON `categories`;
DROP INDEX `name_26` ON `categories`;
DROP INDEX `name_27` ON `categories`;
DROP INDEX `name_28` ON `categories`;
DROP INDEX `name_29` ON `categories`;
DROP INDEX `name_30` ON `categories`;
DROP INDEX `name_31` ON `categories`;
DROP INDEX `name_32` ON `categories`;
DROP INDEX `name_33` ON `categories`;
DROP INDEX `name_34` ON `categories`;
DROP INDEX `name_35` ON `categories`;
DROP INDEX `name_36` ON `categories`;
DROP INDEX `name_37` ON `categories`;

DROP INDEX `sku_prefix_2` ON `categories`;
DROP INDEX `sku_prefix_3` ON `categories`;
DROP INDEX `sku_prefix_4` ON `categories`;
DROP INDEX `sku_prefix_5` ON `categories`;
DROP INDEX `sku_prefix_6` ON `categories`;
DROP INDEX `sku_prefix_7` ON `categories`;
DROP INDEX `sku_prefix_8` ON `categories`;
DROP INDEX `sku_prefix_9` ON `categories`;
DROP INDEX `sku_prefix_10` ON `categories`;
DROP INDEX `sku_prefix_11` ON `categories`;
DROP INDEX `sku_prefix_12` ON `categories`;
DROP INDEX `sku_prefix_13` ON `categories`;
DROP INDEX `sku_prefix_14` ON `categories`;
DROP INDEX `sku_prefix_15` ON `categories`;
DROP INDEX `sku_prefix_16` ON `categories`;
DROP INDEX `sku_prefix_17` ON `categories`;
DROP INDEX `sku_prefix_18` ON `categories`;
DROP INDEX `sku_prefix_19` ON `categories`;
DROP INDEX `sku_prefix_20` ON `categories`;
DROP INDEX `sku_prefix_21` ON `categories`;
DROP INDEX `sku_prefix_22` ON `categories`;
DROP INDEX `sku_prefix_23` ON `categories`;
DROP INDEX `sku_prefix_24` ON `categories`;
DROP INDEX `sku_prefix_25` ON `categories`;
DROP INDEX `sku_prefix_26` ON `categories`;

SELECT 'Done! Remaining indexes:' as status;
SELECT INDEX_NAME FROM information_schema.STATISTICS 
WHERE TABLE_SCHEMA='asset_management' AND TABLE_NAME='categories' 
GROUP BY INDEX_NAME;
